name: Dynamic Lambda Deployment

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'hotfix/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # -------------------------------
      # 🧾 CHECKOUT
      # -------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------------
      # ⚙️ SETUP NODE & VARS
      # -------------------------------
      - name: Setup Node.js and Env Vars
        uses: BreathingCode/terraform-pipeline-template/.github/actions/setup-node@main
        with:
          node_version: '20'

      # -------------------------------
      # 🔧 BUILD & PACKAGE LAMBDA
      # -------------------------------
      - name: Install & Build
        uses: BreathingCode/terraform-pipeline-template/.github/actions/build-package@main
        with:
          project_name: ${{ env.PROJECT_NAME }}
        
      - name: Upload Lambda to S3
        uses: BreathingCode/terraform-pipeline-template/.github/actions/upload-to-s3@main
        with:
          global_env_vars_json: ${{ secrets.GLOBAL_ENV_VARS_JSON }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          project_name: ${{ env.PROJECT_NAME }}

      # -------------------------------
      # ⚙️ TERRAFORM SETUP & TFVARS
      # -------------------------------
      - name: Setup Terraform
        uses: BreathingCode/terraform-pipeline-template/.github/actions/setup-terraform@main
        with:
          terraform_version: '1.5.6'
          environment: ${{ env.ENVIRONMENT }}
          project_name: ${{ env.PROJECT_NAME }}
          s3_bucket_name: ${{ env.S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate tfvars
        uses: BreathingCode/terraform-pipeline-template/.github/actions/generate-tfvars@main
        with:
          environments: ${{ secrets.ENVIRONMENTS }}
          global_env_vars_json: ${{ secrets.GLOBAL_ENV_VARS_JSON }}
          s3_bucket_name: ${{ env.S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          project_name: ${{ env.PROJECT_NAME }}
          environment: ${{ env.ENVIRONMENT }}

      # -------------------------------
      # 🔄 IMPORT & APPLY TERRAFORM
      # -------------------------------
      - name: Importar recursos existentes
        uses: BreathingCode/terraform-pipeline-template/.github/actions/import-resources@main
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          project_name: ${{ env.PROJECT_NAME }}
          environment: ${{ env.ENVIRONMENT }}

      - name: Validar Terraform
        uses: BreathingCode/terraform-pipeline-template/.github/actions/validate-terraform@main

      - name: Terraform Plan and Apply
        uses: BreathingCode/terraform-pipeline-template/.github/actions/plan-apply-terraform@main
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
