name: Dynamic Lambda Deployment

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
      
      - name: Build TypeScript
        run: npm run build

      - name: Setup Environment Variables
        run: echo "PROJECT_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Create Lambda ZIP with node_modules
        run: |
          mkdir -p lambda-package
          cp -r dist/* lambda-package/
          cp -r node_modules lambda-package/
          cp package.json lambda-package/
          cd lambda-package
          zip -r ../${{ env.PROJECT_NAME }}.zip .

      - name: Upload Lambda ZIP to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp ${{ env.PROJECT_NAME }}.zip s3://meu-unico-bucket-s3/${{ env.PROJECT_NAME }}.zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Create environment JSON file for Terraform
        run: |
          cat <<EOF > terraform/lambda-env-vars.auto.tfvars.json
          {
            "lambda_env_vars": ${{ secrets.LAMBDA_ENV_VARS_JSON }},
            "CORS_ORIGIN_PERMISSION": "${{ secrets.CORS_ORIGIN_PERMISSION }}"
          }
          EOF

      - name: Import existing AWS resources
        run: |
          terraform import aws_s3_bucket.lambda_code_bucket meu-unico-bucket-s3 || echo "Bucket already managed"

          terraform import aws_iam_role.lambda_execution_role ${{ env.PROJECT_NAME }}_execution_role || echo "Role already managed"

          terraform import aws_cloudwatch_log_group.lambda_log_group "/aws/lambda/${{ env.PROJECT_NAME }}" || echo "Log group already managed"

          aws lambda get-function --function-name ${{ env.PROJECT_NAME }} \
            --region us-east-1 > /dev/null 2>&1 && \
            terraform import aws_lambda_function.my_lambda_function ${{ env.PROJECT_NAME }} || \
            echo "Lambda function does not exist"

          QUEUE_URL=$(aws sqs get-queue-url --queue-name skeleton-pub-queue --region us-east-1 --query 'QueueUrl' --output text 2>/dev/null)
          if [ -n "$QUEUE_URL" ]; then
            terraform import aws_sqs_queue.skeleton_pub_queue "$QUEUE_URL"
          else
            echo "Queue skeleton-pub-queue does not exist"
          fi

          terraform import aws_lambda_permission.allow_sqs_invoke ${{ env.PROJECT_NAME }}/AllowExecutionFromSQS || echo "Permission already managed"

          MAPPING_UUID=$(aws lambda list-event-source-mappings \
            --function-name ${{ env.PROJECT_NAME }} \
            --event-source arn:aws:sqs:us-east-1:125702582030:skeleton-pub-queue \
            --region us-east-1 \
            --query 'EventSourceMappings[0].UUID' \
            --output text 2>/dev/null)

          if [ "$MAPPING_UUID" != "None" ] && [ -n "$MAPPING_UUID" ]; then
            terraform import aws_lambda_event_source_mapping.from_sqs "$MAPPING_UUID"
          else
            echo "Event Source Mapping not found"
          fi
        continue-on-error: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
